"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Coche_1 = require("./Coche");
var Extra_1 = require("./Extra");
var Carroceria_1 = require("./Carroceria");
var Rueda_1 = require("./Rueda");
var c1 = new Carroceria_1.Carroceria(true, true, false);
var c2 = new Carroceria_1.Carroceria(true, false, true);
var c3 = new Carroceria_1.Carroceria(false, true, true);
var c4 = new Carroceria_1.Carroceria(false, false, false);
var c5 = new Carroceria_1.Carroceria(true, true, true);
var e1 = new Extra_1.Extra(true, 14, true);
var e2 = new Extra_1.Extra(false, 13, true);
var e3 = new Extra_1.Extra(false, 14, true);
var r1 = new Rueda_1.Rueda("Aurora", "lluvia");
var r2 = new Rueda_1.Rueda("Michelin", "seco");
var r3 = new Rueda_1.Rueda("Aplus", "lluvia");
var r4 = new Rueda_1.Rueda("Centara", "seco");
var car1 = new Coche_1.Coche("Seat", "Ibiza", 1780, 4059, 1163, "rojo", [r1, r1, r1, r1], e2, c4);
var car2 = new Coche_1.Coche("Land Rover", "Range Rover Velar", 1930, 4804, 1874, "gris", [r2, r2, r2, r2], e1, c3);
var car3 = new Coche_1.Coche("Land Rover", "Range Rover", 1983, 5000, 2328, "blanco", [r2, r2, r2, r2], e1, c5);
var car4 = new Coche_1.Coche("Audi", "Audi e-tron GT", 1964, 4989, 2420, "plateado", [r3, r3, r3, r3], e1, c5);
console.log("Coche 1:");
car1.mostrarDatos();
console.log("Coche 2:");
car2.mostrarDatos();
console.log("Coche 3:");
car3.mostrarDatos();
